version: '3.8'

services:
    spark-master:
        depends_on:
            - minio
        environment:
            - AWS_ACCESS_KEY_ID=admin
            - AWS_SECRET_ACCESS_KEY=password
            - AWS_REGION=us-east-1
    spark-worker:
        depends_on:
            - spark-master
            - minio
        environment:
            - AWS_ACCESS_KEY_ID=admin
            - AWS_SECRET_ACCESS_KEY=password
            - AWS_REGION=us-east-1
    minio:
        image: minio/minio
        container_name: minio
        environment:
            - MINIO_ROOT_USER=admin
            - MINIO_ROOT_PASSWORD=password
            - MINIO_DOMAIN=minio
        ports:
            - 9001:9001
            - 9000:9000
        command: ['server', '/data', '--console-address', ':9001']
        volumes:
            - minio-data:/data
        networks:
            default:
                aliases:
                    - warehouse.minio # must be name of iceberg warehouse bucket on minio, otherwise host is not found
    mc:
        depends_on:
            - minio
        image: minio/mc
        container_name: mc
        environment:
            - AWS_ACCESS_KEY_ID=admin
            - AWS_SECRET_ACCESS_KEY=password
            - AWS_REGION=us-east-1
        entrypoint: >
            /bin/sh -c "
            until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
            /usr/bin/mc rm -r --force minio/warehouse;
            /usr/bin/mc mb minio/warehouse;
            /usr/bin/mc policy set public minio/warehouse;
            tail -f /dev/null
            "
    catalog:
        image: postgres:15-alpine
        container_name: pg_catalog
        environment:
            - POSTGRES_USER=iceberg
            - POSTGRES_PASSWORD=iceberg
            - POSTGRES_DB=iceberg
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'iceberg']
            interval: 5s
            retries: 5
        ports:
            - '5432:5432'
        volumes:
            - catalog-data:/var/lib/postgresql/data

volumes:
    minio-data:
    catalog-data:
