version: '3.8'

x-spark-common: &spark-common
    build:
        context: .
        dockerfile: docker/Dockerfile
        target: spark
    environment:
        - SPARK_NO_DAEMONIZE=true
    env_file:
        - .env
    volumes:
        - ./apps:/opt/spark/apps
        - spark-logs:/opt/spark/spark-events
        - ./workspace:/opt/workspace

services:
    spark-master:
        <<: *spark-common
        container_name: spark-master
        entrypoint: ['./entrypoint.sh', 'master']
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8080']
            interval: 5s
            timeout: 3s
            retries: 3
        ports:
            - '9090:8080' # web ui
            - '7077:7077' # master

    spark-history:
        <<: *spark-common
        container_name: spark-history
        entrypoint: ['./entrypoint.sh', 'history']
        depends_on:
            - spark-master
        ports:
            - '18080:18080'

    spark-worker:
        <<: *spark-common
        entrypoint: ['./entrypoint.sh', 'worker']
        depends_on:
            - spark-master
        env_file:
            - .env

    jupyterlab:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: jupyterlab
        container_name: jupyterlab
        depends_on:
            - spark-master
        ports:
            - '8889:8888'
        volumes:
            - ./workspace:/opt/workspace

volumes:
    spark-logs:
